on:
  push:
    tags:
      - '*'

name: Create Release

jobs:
  build:
    name: Build wheels
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: sdsstools ${{ github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build

      - name: Build wheels
        run: |
          pyproject-build -w

      - name: Build source
        run: |
          pyproject-build -s

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
